config/routes.rb
Rails.application.routes.draw do
  root 'publicacoes#index'
  resources :publicacoes
end

app/models/publicacao.rb
class Publicacao < ActiveRecord::Base
  belongs_to :publicacao
  has_many :publicacaos
PublicacaoValidator
  validates(:conteudo, presence: true)
  include ActiveModel::Validations
  validates_with PublicacaoValidator

  def to_s
     return "#{created_at.strftime('%F %T')} #{conteudo}";
  end
end

app/models/publicacao_validator.rb
class PublicacaoValidator < ActiveModel::Validator
   INVALIDAS = %w(verde azul)

   def validate(publicacao)
	INVALIDAS.each do |invalida|
	   if(!publicacao.conteudo.downcase.match("(^|\s)#{invalida}(\s|$)").nil?)
		publicacao.errors[:base] << invalida
            end
         end
   end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/publicacoes_controller.rb
class PublicacoesController < ApplicationController
  
  def index
    # inicializando uma nova publicação
    @publicacao = Publicacao.new
    # buscando somente as publicações "raízes"
    @publicacoes = Publicacao.where(publicacao_id: nil).order('created_at DESC').paginate(page: params[:page], per_page: 10)
  end

  def show
     @publicacao = Publicacao.find(params[:id])
  end

  def create
     @publicacao = Publicacao.new(publicacao_params)
     @publicacao.save
     index
     render "index"
  end

  def update
     @publicacao = Publicacao.find(params[:id])
     nova = @publicacao.publicacaos.build(conteudo: params[:conteudo]);
     if(@publicacao.valid?)
	nova.save!
        return render json: nova
     end 
     return render json: nova.errors
  end

  private

    def publicacao_params
      params.require(:publicacao).permit(:conteudo)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Retorna o título completo da página requisitada
  def full_title(page_title = '')
    base_title = "Threads"
    if page_title.empty?
      return base_title
    else
      return "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/publicacoes_helper.rb
module PublicacoesHelper

   # imprime uma publicação em formato de árvore
   def imprimir(publicacao)
      arvore = "";
      arvore << "<ol>" if publicacao.publicacao.nil?;
      arvore << "<li>#{publicacao}<input id='bt_reply$#{publicacao.id}' type='button' value='reply' onclick='comentar(this)' />";
      
      if !publicacao.publicacaos.empty?
          arvore << "<ol>" 
          filhos = ordenar(publicacao.publicacaos)
          filhos.each do |p|
             arvore << imprimir(p);
 	  end
          arvore << "</ol>"
      end 

      arvore << "</li>"
      arvore << "</ol>" if publicacao.publicacao.nil?;
      return arvore;
   end

   def ordenar(publicacoes)
	publicacoes.sort_by {|e| e.created_at}.reverse
   end
 
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    @Copyright. 2014. Vinícius Fernandes Moreira.
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "[Home]", root_path, id: "logo" %>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/publicacoes/index.html.erb
<div class="new_publicacao">
   <%= form_for(@publicacao, url: publicacoes_path(@publicacao)) do |p| %>
 	<%= p.text_area :conteudo %>
	<%= p.submit "Submit Query", class: "btn btn-primary" %>
   <% end %>
</div>

<ol>
  <% @publicacoes.each do |p| %>
    <li><%= link_to p, "#{publicacoes_path}/#{p.id}" %></li>
  <% end %>
</ol>

<%= will_paginate %>

app/views/publicacoes/new.html.erb
<h1>Publicacoes#new</h1>
<p>Find me in app/views/publicacoes/new.html.erb</p>

app/views/publicacoes/show.html.erb
<%= imprimir(@publicacao).html_safe %>
<span id="url_path" style="visibility:hidden"><%= publicacoes_path %></span>